### PR TITLE
MVP implementation

### PR DESCRIPTION
**Pull request by manolo**
Connects to https://github.com/vaadin/vaadin-core/issues/105

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-box/2)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[bower.json, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm4UNk5DzqXmeDbdRo:-Kwm4UNk5DzqXmeDbdRp:b-120pyr) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/bower.json#L30)):*
> ```JSON
>     "vaadin-themable-mixin": "^1.1.3",
>     "vaadin-item": "^1.0.0",
>     "vaadin-list-mixin": "vaadin/vaadin-list-mixin#change-selection"
> ```

Depending on a branch will break this once the branch gets merged+deleted

---

*[vaadin-list-box.html, line 10 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm47H9fnggQ-RiJS55:-Kwm47H9fnggQ-RiJS56:bj8cwck) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L10)):*
> ```HTML
> <link rel="import" href="../vaadin-themable-mixin/vaadin-themable-mixin.html">
> <link rel="import" href="../vaadin-list-mixin/vaadin-list-mixin.html">
> <dom-module id="vaadin-list-box-default-theme">
> ```

Should probably use a copy of the -tabs default theme?

---

*[vaadin-list-box.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2Rv-0HZE6PuWkY0q:-Kwm2Rv-0HZE6PuWkY0r:botyex6) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L49)):*
> ```HTML
>     }
>     </style>
>     <div id="scroll" part="items">
> ```

Unnecessary id

---

*[vaadin-list-box.html, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2C9b6n6yNjKfXu0N:-Kwm2C9cUR0ZBq07J-zF:bw2sif4) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L69)):*
> ```HTML
>        *
>        * ### Styling
>        *
> ```

Generic styling link missing

---

*[vaadin-list-box.html, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm1hgps6ElkxAu403d:-Kwm1hgqdSFUbjzegZps:b-8ixkon) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L90)):*
> ```HTML
> 
>             // We need to set this property, but don't want users to override it.
>             /** @private */
> ```

If the listbox can only be vertical, then it shouldn't have `vertical` flag at all. And all functionality related to `vertical` should be moved from the mixin to tabs if vertical is tabs specific thing.

---

*[demo/list-box-basic-demos.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm3XS5S5luClqVkxqL:-Kwm3XS5S5luClqVkxqM:b3203pk) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/demo/list-box-basic-demos.html#L37)):*
> ```HTML
>           vaadin-list-box {
>             width: 140px;
>             box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2);
> ```

The demo should use vaadin-list-box default styles

---

*[test/list-box-test.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2kZB5uhNUqUVwYyz:-Kwm2kZB5uhNUqUVwYz-:byp1ktf) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/test/list-box-test.html#L22)):*
> ```HTML
> 
>   <script>
>     describe('sample test', () => {
> ```

Rename

---

*[test/list-box-test.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm3JvniPtnu0SuHLyp:-Kwm3JvniPtnu0SuHLyq:bbyzrz6) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/test/list-box-test.html#L31)):*
> ```HTML
>       });
> 
>       it('should have an unnamed slot for label', () => {
> ```

What label?

---

*[test/list-box-test.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm33DYftpY95ZpkzY1:-Kwm33DYftpY95ZpkzY2:bzhpa8b) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/test/list-box-test.html#L32)):*
> ```HTML
> 
>       it('should have an unnamed slot for label', () => {
>         const slot = listbox.root.querySelector('slot:not([name])');
> ```

nit: .root -> .shadowRoot

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by manolo** [comment]
Review status: 0 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[bower.json, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm4UNk5DzqXmeDbdRo:-Kwnnv-3oGhlh6npYdgq:bu0zi9g) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/bower.json#L30)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Depending on a branch will break this once the branch gets merged+deleted
</blockquote></details>

That is intentional and temporary until the other PR is merged. I would like to leave here a comment , but not possible in json. 
It will be changed when the PRs is ready for merging

---

*[vaadin-list-box.html, line 10 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm47H9fnggQ-RiJS55:-KwnoKNRT3dpY8YMByQ_:b-tjq2qw) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L10)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should probably use a copy of the -tabs default theme?
</blockquote></details>

You mean border left, etc? 
I tried that but does not looks a proper menu. So I opted by using a neutral styling until @jouni proposes some changes. I would leave those Styling changes for a separated PR out of the MVP

---

*[vaadin-list-box.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2Rv-0HZE6PuWkY0q:-Kwo1JTfXLMl6rygIWKt:b-ibebu1) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L49)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Unnecessary id
</blockquote></details>

There are many components where we use `id` when the element is needed in code.
Done.

---

*[vaadin-list-box.html, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2C9b6n6yNjKfXu0N:-KwnzLE-rdXEJPfnpySL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L69)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Generic styling link missing
</blockquote></details>

Done.

---

*[vaadin-list-box.html, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm1hgps6ElkxAu403d:-KwnzWMjIRQoxiXmzg1W:bcgezbh) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L90)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If the listbox can only be vertical, then it shouldn't have `vertical` flag at all. And all functionality related to `vertical` should be moved from the mixin to tabs if vertical is tabs specific thing.
</blockquote></details>

There could be more elements in the future that might be horizontal or vertical.
Even list-box might be horizontal (ping @jouni) , but I assumed that we only need one 
IMO the mixin is featured for vertical, horizontal or both directions, list-box just uses a case.
I have tried to quick separate the horizontal code to tabs and the code complicates since we need to override almost mixin methods.
In this way the code is much simpler and reusable.

---

*[demo/list-box-basic-demos.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm3XS5S5luClqVkxqL:-Kwo-w0r8D7MVG1qR-qC:b1zrrmq) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/demo/list-box-basic-demos.html#L37)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The demo should use vaadin-list-box default styles
</blockquote></details>

The box here is intentional to make the demo look better when adding some additional elements.
Default theme of the list-box shouldn't have any box, that is the reason of showing the user how to add a box.

---

*[test/list-box-test.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2kZB5uhNUqUVwYyz:-Kwo0Sp5lQ6N3K1h4EFp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/test/list-box-test.html#L22)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.

---

*[test/list-box-test.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm3JvniPtnu0SuHLyp:-Kwo0Vgxny1mx-ONbU5l:b-debibl) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/test/list-box-test.html#L31)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

What label?
</blockquote></details>

copied and pasted.
Done.

---

*[test/list-box-test.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm33DYftpY95ZpkzY1:-Kwo1TElyLKaj7DCx8yc:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/test/list-box-test.html#L32)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

nit: .root -> .shadowRoot
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by tomivirkki** [comment]
*[vaadin-list-box.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2Rv-0HZE6PuWkY0q:-Kwo3JQbKFz8r-Z0Lwug:bfo1l4u) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L49)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

There are many components where we use `id` when the element is needed in code.
Done.
</blockquote></details>

Yeah, we should gradually get rid of those, not add more

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by tomivirkki** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-list-box.html, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2C9b6n6yNjKfXu0N:-Kwo3WRfafweXvZBWHtm:b-ezs9x6) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L69)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should be under "Styling" like in https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L148

---

*[vaadin-list-box.html, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm1hgps6ElkxAu403d:-Kwo3nOOt-j9FSWbKLG3:b-kn67jf) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L90)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

There could be more elements in the future that might be horizontal or vertical.
Even list-box might be horizontal (ping @jouni) , but I assumed that we only need one 
IMO the mixin is featured for vertical, horizontal or both directions, list-box just uses a case.
I have tried to quick separate the horizontal code to tabs and the code complicates since we need to override almost mixin methods.
In this way the code is much simpler and reusable.
</blockquote></details>

"Could be" is not a valid justification. Ideally list-mixin should only have functionality that's shared between _all_ elements that extend it. `vertical` doesn't make any sense for `<vaadin-list-box>` and it will also add unnecessary `vertical` attribute to all the children that's quite confusing.

"Even list-box might be horizontal" well how would you make the listbox horizontal then since vertical is the default? For that case we should add `horizontal` property to listbox but it wouldn't again make sense to add it to -mixin. Alternative fix for this would be to switch from `vertical` property to `orientation` and have different default values for the property in listbox and tabs.

---

*[demo/list-box-basic-demos.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm3XS5S5luClqVkxqL:-Kwo5ZVuX6aABSyTJLe0:b4a9enm) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/demo/list-box-basic-demos.html#L37)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The box here is intentional to make the demo look better when adding some additional elements.
Default theme of the list-box shouldn't have any box, that is the reason of showing the user how to add a box.
</blockquote></details>

Our demos are for presenting element core functionality, not themability. All the other elements use default theme in the demos.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by manolo** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-list-box.html, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm2C9b6n6yNjKfXu0N:-Kwo8F3XdHRWOwxBo3s-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L69)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should be under "Styling" like in https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L148
</blockquote></details>

Done.

---

*[vaadin-list-box.html, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm1hgps6ElkxAu403d:-Kwo6sjoKR6lJOWle80S:b9i54k) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L90)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"Could be" is not a valid justification. Ideally list-mixin should only have functionality that's shared between _all_ elements that extend it. `vertical` doesn't make any sense for `<vaadin-list-box>` and it will also add unnecessary `vertical` attribute to all the children that's quite confusing.

"Even list-box might be horizontal" well how would you make the listbox horizontal then since vertical is the default? For that case we should add `horizontal` property to listbox but it wouldn't again make sense to add it to -mixin. Alternative fix for this would be to switch from `vertical` property to `orientation` and have different default values for the property in listbox and tabs.
</blockquote></details>

Anyways, IMO this seems the simpler way to have related code centralised in one place.
I don't see any strong advantage of moving one part of the code and repeating another part in tabs.
 
But anyways, that should be done in different task, must not block this PR

---

*[demo/list-box-basic-demos.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm3XS5S5luClqVkxqL:-Kwo8IHdFRsI6dRz_iuZ:b47gxo8) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/demo/list-box-basic-demos.html#L37)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Our demos are for presenting element core functionality, not themability. All the other elements use default theme in the demos.
</blockquote></details>

Not a strong reason here, just aesthetical. Done. 




---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by tomivirkki** [comment]
*[demo/list-box-basic-demos.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm3XS5S5luClqVkxqL:-KwoD4_EV8YNe2r7ApX4:b-axgu4d) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/demo/list-box-basic-demos.html#L37)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Not a strong reason here, just aesthetical. Done. 




</blockquote></details>

:+1: Now it's better aligned with tabs also https://www.dropbox.com/s/4m5yekznz07niix/Screenshot%202017-10-19%2013.34.46.png?dl=0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by tomivirkki** [comment]
*[vaadin-list-box.html, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm1hgps6ElkxAu403d:-KwoCOLr4MbT7As1oRXp:b67d3my) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/vaadin-list-box.html#L90)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Anyways, IMO this seems the simpler way to have related code centralised in one place.
I don't see any strong advantage of moving one part of the code and repeating another part in tabs.
 
But anyways, that should be done in different task, must not block this PR
</blockquote></details>

Well as long as this issue gets fixed (later is fine).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by manolo** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-Kwm4UNk5DzqXmeDbdRo:-KwoFeA6Ri2WrSruFYbI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/37d6b8a92029b3815fba03e1669e6cabcd0db2b2/bower.json#L30)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

That is intentional and temporary until the other PR is merged. I would like to leave here a comment , but not possible in json. 
It will be changed when the PRs is ready for merging
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 10 of 15 files at r1, 7 of 7 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-:-KwoavSxxE_7L3P9kkXG:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/list-box-basic-demos.html, line 32 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2#-KwoZEnGCyF7Y0x7ABNA:-KwoaxuM-4Df1wqXCRVW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-box/blob/e29791534e8102681a85976348e9977cb4b8a2c7/demo/list-box-basic-demos.html#L32)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

nit: change the id, so it will be different from the first one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/2)*

**Pull request merged**
