### PR TITLE
Default styles and Visual tests

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/vaadin-core/issues/105

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-box/5)

### CODE REVIEW

**Comment by manolo** [comment]
Those spaces are added by formatter, the convention is ident two spaces inside the style tag, now they are aligned with other blocks

**Comment by jouni** [comment]
Ah, you’re absolutely right! I can only blame my poor eyesight 🤦‍♂️ 

So seems like everything is in order then!

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/5#-:-KxMRqFKQZnJjHoKilKe:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-box/5)*

**Pull request merged**
